name: pretty_logger
description: "Pretty wrapper for logger"
version: 0.0.1

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.4.0
  rxdart: ^0.28.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:


flutter:
  uses-material-design: true

